#+hugo_base_dir: .
#+hugo_section: ./post

#+hugo_weight: auto

* Projects                                                        :@projects:
* Meta                                                                :@meta:
** DONE Welcome
:PROPERTIES:
:EXPORT_DATE: 2017-10-01
:EXPORT_FILE_NAME: welcome
:END:

Dear residents of Castine,

I am asking for your vote on November 7, 2017 for the privilage of becoming your
next selectman. 

Responsible governance does not appear out of thin air. It does not show up
because we want it. It is the hard work of dedicated individuals who are
passionate about their town.

As your next selectman:

I promise to be a passionate supporter of Castine and
all our shared friends and neighbors.

I promise to be relentlessly optimistic about the future of this town, and to
uphold the vision statement crafted years ago to make this a thriving year-round
commuinity.

I promise to be responsive and responsible to you, the citizens of Castine.

And most of all, I promise to listen carefully to your ideas, concerns and
desires.

In order to do all those things, we need more participation in local governance.
We need people to feel that they are listened to, whether action is taken or
not. And decisions need to be communicated in as many different ways as there
are people in our town.

I am committed to raising my family in Castine, and hope that you will join me
in helping make Castine thrive.

Sincerely,
Colin Powell
** DONE Thank you
:PROPERTIES:
:EXPORT_DATE: 2017-11-07
:EXPORT_FILE_NAME: thank-you
:END:

Castine voters, 

Thank you so much for your passionate support and most
especially your vote at the polls this year! When you choose to run for public
office, there is a vulnerability that you must reconcile before you get to work
changing hearts and minds with your ideas. That reconciliation happened so
quickly for me in this election primarily because this town is such a positive,
supportive community.

Folk singer Greg Brown has a live album on which, in between two songs, he tells
a story about living in a small town in the Upper Peninsula of Michigan. Winters
are hard in the UP, and he explained that you have to know your neighbors when
the weather howls, and life throws challenges in your path.  Community is
created when we need each other, not when we want community. "You have to need
each other," says Brown. 

I need you! And I need my neighbors. Let's embrace that need and get work moving
Castine into the future. Please communicate with me early and often with your
ideas. I can't promise I'll act on all of them, but the only way we know what
people need is by communicating with one another.

In the next few weeks I'll be working with my fellow selectpeople to setup some
new lines of communication with the municipal government. I'll also be touring
town facilities and talking with town employees about what they need, or see as
needs for other members of our community.

Thank you again, and I am so excited to be your next selectperson!

* Business                                                        :@business:
** DONE Our Merchants Need Our Help!
:PROPERTIES:
:EXPORT_DATE: 2017-10-27
:EXPORT_FILE_NAME: merchants-need-our-help
:END:

Friends,

I believe the Town of Castine can and should do more to support our merchants. We often talk about attracting families to Castine to rent or buy, but when you ask most folks how they found Castine they've either been here their whole lives (summer, student, long-time resident), or they discovered it on a vacation or a day-trip.

When I helped start the Castine Farmers' Market almost a decade ago, there were vendors and farmers excited to sell who had never actually been to Castine before. They lived in Ellsworth. That should not happen, and I think the town can do a better job of advertising the facilities we have and adding facilities we don't have to attract more day-trippers and weekend vacationers.

That starts with supporting our merchants. Speaking with the head of the Castine Merchant's Association yesterday, I discovered that the Visitor's Center has been a huge success the past few years, but that the merchants need help keeping it going. I would like to work with the merchant's association, perhaps attending their meetings as a non-voting participant, and working through the challenges of running a business in Castine and addressing their concerns with honesty and optimism.

Let's build a stronger Castine, one business at a time!
* MMA                                                                  :@mma:
** DONE Interconnected
:PROPERTIES:
:EXPORT_DATE: 2017-11-10
:EXPORT_FILE_NAME: interconnected
:END:

Had a nice introduction to the MMA Board of Trustees this morning. Town Manager
Jimmy Goodson notified the Board that Dave Unger had finished his tenure on the
selectboard and that I was stepping into the role. I received a warm applause
and good conversation after the meeting adjourned.

I also had a fascinating conversation with Trustee Bob Peacock from Eastport
about the impact of the two major hurricanes in Texas and Florida on the
restaurant and food distribution industries, which is the focus of his company.
Amazing to reflect on how interconnected our world has become and how storms can
affect seemingly unrelated parts of our lives.

I think the same observation extends to our town, and I think that as we embark
on improving the state of rental property in Castine, we should do so in concert
with property owners so we can minimize the unintended consequence of changes to
town policy.
* Utilities                                                      :@utilities:
** DONE What's in your wastewater?
:PROPERTIES:
:EXPORT_DATE: 2018-03-26
:EXPORT_FILE_NAME: wastewater
:END:

Would you believe medications flushed down the toilet can actually be read in
our wastewater facility? Pills do not dissolve as quickly as you may think, and
that may be a good thing. While a recent event allowed a municipal employee to
be able to identify a particular medication type that came through our treatment
facility, the real story is that this happened at all.

Disposing of things can be tricky business. It's not always clear what one
should do with things they don't want anymore, especially for things like
controlled substances. What we can emphatically say you should NOT do, is flush
things down the toilet. The Town of Castine spends a lot of resources carefully
removing most waste products from the water that goes down your drains, toilets
and outdoor sewers. Thus, when you introduce things into that water stream that
are non-standard, the wastewater facility has to deal with it.

In this case, prescription or over-the-counter medications are a significant
problem. In large urban areas, studies are beginning to discover serious issues
with medications reaching our public water supplies, oceans, lakes and rivers. A
few weeks ago, one of our wastewater facility employees discovered anti-seizure
medications that had gone down the drain. While these pills were caught, easy
dissolving pills might not have, and that medication would have joined the
(mostly clean) wastewater as it is disposed of via over-board discharge into
Oakum Bay.

When you're flushing something, ask yourself, would I want to see this in
Castine Harbor? If the answer is no, call Town Hall and ask for the appropriate
way to dispose of your waste. In the case of medications, you can take them to
the Bucksport Police Department or the Hancock County Sheriff's office in
Ellsworth. Either location will happily and safely dispose of them for free.
